create table if not exists items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  seller_name text not null default 'Jose Store',
  store_slug text not null default 'jose-store',
  name text not null,
  slug text unique not null,
  brand text,
  category text,
  cost numeric default 0,
  price numeric default 0,
  quantity integer default 1,
  condition text default 'Good',
  location text default 'Alpharetta',
  description text default '',
  title_en text,
  title_es text,
  description_en text,
  description_es text,
  paypal_url text default '#',
  cashapp_url text default '#',
  zelle_info text default '#'
);

create table if not exists buyer_inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  buyer_name text not null,
  buyer_contact text,
  item_name text,
  inquiry text,
  status text default 'New'
);

alter table items enable row level security;
alter table buyer_inquiries enable row level security;
